### ISSUE TITLE
大佬 你的那个代码跑不出来 没有train.csv 可以提供下吗

### ISSUE THREAD

**Issue by cutbuzz** [yearing1017/Global-Wheat-Detection#6]
mirzat0507@gmail.com
![image](https://user-images.githubusercontent.com/84438684/122648114-2e5c6100-d15a-11eb-90f1-bbe8098a58bc.png)

**Comment by yearing1017** [comment]
现在比赛链接不能下载数据了吗  不能的话我得找一下 因为好久没用了  顺利找到就发你


| |
yearing1017
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月19日 ***@***.***> 写道：

***@***.***
